version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    executor:
      name: win/vs2019
      shell: powershell.exe
    steps:
      - checkout
      - run:
          name: "Install project dependencies"
          command: $a = 1; echo $a; $a
      - run:
          name: "Run Build step"
          command: $a  
