version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    executor:
      name: win/vs2019
      shell: powershell.exe
    steps:
      - checkout
      - run:
          name: "Run version step" 
          command: $CIRCLE_BRANCH
       - run:
          name: "Run version step2" 
          command: $CIRCLE_WORKFLOW_I     
