version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    executor:
      name: win/vs2019
      shell: powershell.exe
    steps:
      - run:
          name: "Install project dependencies"
          command: echo ${CIRCLE_BRANCH}
      - run: echo "This is pipeline ID << pipeline.id >>"
      - run: echo "This is pipeline ID << pipeline.number >>"
      - run: echo "This is pipeline ID << pipeline.project.type >>"
      - run: echo "This is pipeline ID << pipeline.git.branch >>"
      - run: echo pipeline.number; pipeline.number
      - run: pipeline.git.branch\.pipeline.number
